// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlOH1jD7CpZbd9JvO3S-YhJUgRlAs1t0',
    appId: '1:817175194387:web:d60e0c17318768879e88e6',
    messagingSenderId: '817175194387',
    projectId: 'gamify-d9556',
    authDomain: 'gamify-d9556.firebaseapp.com',
    storageBucket: 'gamify-d9556.appspot.com',
    measurementId: 'G-TW1TVHJJ7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaCffw92y7UsflefxALGvjZrhzzapSlFQ',
    appId: '1:817175194387:android:ad7446b35aa1a8439e88e6',
    messagingSenderId: '817175194387',
    projectId: 'gamify-d9556',
    storageBucket: 'gamify-d9556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs9lie7Rj7JYPDJwefJ-FitoVJm8fhtHU',
    appId: '1:817175194387:ios:b69b016f6ebad3219e88e6',
    messagingSenderId: '817175194387',
    projectId: 'gamify-d9556',
    storageBucket: 'gamify-d9556.appspot.com',
    iosClientId: '817175194387-81ph8jcm1f0hp4n58fa81t7n41jmphp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs9lie7Rj7JYPDJwefJ-FitoVJm8fhtHU',
    appId: '1:817175194387:ios:b69b016f6ebad3219e88e6',
    messagingSenderId: '817175194387',
    projectId: 'gamify-d9556',
    storageBucket: 'gamify-d9556.appspot.com',
    iosClientId: '817175194387-81ph8jcm1f0hp4n58fa81t7n41jmphp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamify',
  );
}
